In [1]:
import pandas as pd

In [2]:
kpi_df = pd.read_csv("data/gold/fraud_kpis.csv")

kpi_df

,total_transactions,total_fraud_cases,fraud_rate_percent,high_risk_transactions,international_transactions,suspicious_transactions,approved_transactions,declined_transactions,total_transaction_amount
0,1000,245,24.5,360,732,260,482,518,2377353.22

In [3]:
merchant_df = pd.read_csv("data/gold/merchant_fraud_analysis.csv")

merchant_df.head(10)

,merchant,total_transactions,fraud_cases,total_amount,fraud_rate_percent
0,Acosta Inc,1,0,3199.95,0.0
1,Acosta-Roberts,1,0,620.58,0.0
2,Adams PLC,1,0,2599.20,0.0
3,Adams and Sons,1,0,1426.77,0.0
4,"Aguilar, Carney and Hancock",1,0,3562.54,0.0
5,"Alexander, Jones and Harris",1,1,4582.50,100.0
6,"Alexander, Williams and Rivas",1,0,1319.52,0.0
7,Alexander-Davila,1,1,112.20,100.0
8,Allen-Rios,1,0,2292.21,0.0
9,Anderson Ltd,1,1,4998.68,100.0

In [4]:
country_df = pd.read_csv("data/gold/country_risk_analysis.csv")

country_df

  country  total_transactions  fraud_cases  suspicious_transactions
0      CA                 244           62                       88
1      NG                 267           63                       84
2      UK                 221           60                       88
3      US                 268           60                        0

In [5]:
approval_df = pd.read_csv("data/gold/approval_analysis.csv")

approval_df

     status  total_transactions  total_amount
0  approved                 482    1127433.70
1  declined                 518    1249919.52